name: rio-tiler
channels:
- defaults
dependencies:
- appnope=0.1.0=py36_0
- bleach=1.5.0=py36_0
- boto3=1.4.5=py36_0
- botocore=1.5.92=py36_0
- certifi=2016.2.28=py36_0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- docutils=0.14=py36_0
- entrypoints=0.2.3=py36_0
- freetype=2.5.5=2
- html5lib=0.999=py36_0
- icu=54.1=0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jbig=2.1=0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jmespath=0.9.0=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.3.0=py36_0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- markupsafe=1.0=py36_0
- matplotlib=2.0.2=np113py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.3=0
- nbconvert=5.2.1=py36_0
- nbformat=4.4.0=py36_0
- networkx=1.11=py36_0
- notebook=5.0.0=py36_0
- numpy=1.13.1=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pandocfilters=1.4.2=py36_0
- path.py=10.3.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np113py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=2
- qtconsole=4.3.1=py36_0
- readline=6.2=2
- s3transfer=0.1.10=py36_0
- scikit-image=0.13.0=np113py36_0
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_1
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.18=0
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=3.0.2=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - affine==2.1.0
  - attrs==17.2.0
  - cachetools==2.0.1
  - chardet==3.0.4
  - click==6.7
  - click-plugins==1.0.3
  - cligj==0.4.0
  - future==0.16.0
  - idna==2.6
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - memory-profiler==0.48.0
  - mercantile==0.10.0
  - oauthlib==2.0.6
  - prompt-toolkit==1.0.15
  - psutil==5.4.1
  - pyproj==1.9.5.1
  - pysocks==1.6.7
  - python-twitter (/Users/thead/git/sentinel2-bot/src/python-twitter)==3.1
  - rasterio==1.0a10
  - requests==2.18.4
  - requests-oauthlib==0.8.0
  - rio-mucho==0.2.2
  - rio-pansharpen==0.2.0
  - rio-tiler (/Users/thead/git/rio-tiler)==0.0.1
  - rio-toa==0.3.0
  - snuggs==1.4.1
  - urllib3==1.22
prefix: /Users/thead/anaconda/envs/rio-tiler

